# python script that depends on one external library
FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt . 
RUN pip install -r requirements.txt 

COPY python-dependency-script.py .

CMD ["python", "python-dependency-script.py"]
