# python script that depends on one external library
FROM python:3.12-slim

RUN pip install -r requrements.txt 

WORKDIR /app

COPY python-dependency-script.py /app

CMD ["python", "python-dependency-script.py"]
